# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InfoForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(300, 780)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(300, 0))
        Dialog.setMaximumSize(QtCore.QSize(300, 16777215))
        Dialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.conversationTitle = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.conversationTitle.setFont(font)
        self.conversationTitle.setObjectName("conversationTitle")
        self.verticalLayout_2.addWidget(self.conversationTitle)
        self.membersLabel = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.membersLabel.setFont(font)
        self.membersLabel.setObjectName("membersLabel")
        self.verticalLayout_2.addWidget(self.membersLabel)
        self.membersList = QtWidgets.QListWidget(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.membersList.setFont(font)
        self.membersList.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.membersList.setGridSize(QtCore.QSize(0, 30))
        self.membersList.setObjectName("membersList")
        self.verticalLayout_2.addWidget(self.membersList)
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.memberNickname = QtWidgets.QLineEdit(self.widget)
        self.memberNickname.setObjectName("memberNickname")
        self.horizontalLayout.addWidget(self.memberNickname)
        self.addMemberButton = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addMemberButton.sizePolicy().hasHeightForWidth())
        self.addMemberButton.setSizePolicy(sizePolicy)
        self.addMemberButton.setMaximumSize(QtCore.QSize(60, 16777215))
        self.addMemberButton.setObjectName("addMemberButton")
        self.horizontalLayout.addWidget(self.addMemberButton, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Conversation info"))
        self.conversationTitle.setText(_translate("Dialog", "kazzart"))
        self.membersLabel.setText(_translate("Dialog", "Members"))
        self.label.setText(_translate("Dialog", "Add member to group chat"))
        self.addMemberButton.setText(_translate("Dialog", "Add"))
