# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StarConversationForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConversationForm(object):
    def setupUi(self, ConversationForm):
        ConversationForm.setObjectName("ConversationForm")
        ConversationForm.setWindowModality(QtCore.Qt.ApplicationModal)
        ConversationForm.resize(400, 170)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ConversationForm.sizePolicy().hasHeightForWidth())
        ConversationForm.setSizePolicy(sizePolicy)
        ConversationForm.setMinimumSize(QtCore.QSize(400, 170))
        ConversationForm.setMaximumSize(QtCore.QSize(400, 170))
        ConversationForm.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(ConversationForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(ConversationForm)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.personNick = QtWidgets.QLineEdit(self.widget_2)
        self.personNick.setObjectName("personNick")
        self.horizontalLayout.addWidget(self.personNick)
        self.startDialogButton = QtWidgets.QPushButton(self.widget_2)
        self.startDialogButton.setObjectName("startDialogButton")
        self.horizontalLayout.addWidget(self.startDialogButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.widget_2, 0, QtCore.Qt.AlignTop)
        self.widget = QtWidgets.QWidget(ConversationForm)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.chatTitle = QtWidgets.QLineEdit(self.widget)
        self.chatTitle.setObjectName("chatTitle")
        self.horizontalLayout_2.addWidget(self.chatTitle)
        self.startChatButton = QtWidgets.QPushButton(self.widget)
        self.startChatButton.setObjectName("startChatButton")
        self.horizontalLayout_2.addWidget(self.startChatButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.widget, 0, QtCore.Qt.AlignTop)

        self.retranslateUi(ConversationForm)
        QtCore.QMetaObject.connectSlotsByName(ConversationForm)

    def retranslateUi(self, ConversationForm):
        _translate = QtCore.QCoreApplication.translate
        ConversationForm.setWindowTitle(_translate("ConversationForm", "Starting new conversation"))
        self.label.setText(_translate("ConversationForm", "Person\'s nickname"))
        self.startDialogButton.setText(_translate("ConversationForm", "Start dialog"))
        self.label_2.setText(_translate("ConversationForm", "Group chat title"))
        self.startChatButton.setText(_translate("ConversationForm", "Create chat"))
